# Server properties
server:
  port: 8110

# Information for the info endpoint
info:
  app:
    environment: DEV
    name: ${spring.application.name}
    description: Account Service - Local Instance

# Spring application properties
spring:
  application:
    name: users-account
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:discovery://config-server
      - optional:file:./env.properties
  datasource:
    url: ${DB_URI:jdbc:h2:mem:testdb}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}

# Eureka configuration
eureka:
  client:
    fetchRegistry: ${EUREKA_DISCOVERY_ENABLED:false}
    registerWithEureka: ${EUREKA_DISCOVERY_ENABLED:false}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

# RabbitMQ settings
rabbitmq:
  exchange: ${RMQ_EXCHANGE:vsp}
  queues:
    verify-account: ${RMQ_VERIFY_ACCOUNT_Q:dummy-queue}
  routing-keys:
    create-credentials: ${RMQ_CREATE_CREDENTIALS_RK:dummy-key}
    profile-setup: ${RMQ_PROFILE_SETUP_RK:dummy-key}
    verify-account: ${RMQ_VERIFY_ACCOUNT_RK:dummy-key}
    reset-passcode: ${RMQ_RESET_PASSCODE_RK:dummy-key}
    delete-user-data: ${RMQ_DELETE_USER_DATA_RK:dummy-key}

# Management properties
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, refresh

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.mariuszilinskas.vsp: DEBUG
