# Server properties
server:
  port: 8110

# Information for the info endpoint
info:
  app:
    environment: DEV
    name: ${spring.application.name}
    description: Account Service - Local Instance

# Spring application properties
spring:
  application:
    name: users-account
  profiles:
    active: dev
  config:
    import:
      - optional:configserver:discovery://config-server
      - optional:file:./env.properties
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER_CLASS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: ${DB_DIALECT}
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}

# Eureka configuration
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
  instance:
    preferIpAddress: true

# RabbitMQ settings
rabbitmq:
  exchange: ${RMQ_EXCHANGE}
  queues:
    verify-account: ${RMQ_VERIFY_ACCOUNT_Q}
  routing-keys:
    create-credentials: ${RMQ_CREATE_CREDENTIALS_RK}
    profile-setup: ${RMQ_PROFILE_SETUP_RK}
    verify-account: ${RMQ_VERIFY_ACCOUNT_RK}
    reset-passcode: ${RMQ_RESET_PASSCODE_RK}
    delete-user-data: ${RMQ_DELETE_USER_DATA_RK}

# Management properties
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, refresh

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.mariuszilinskas.vsp: DEBUG
