name: Build

on:
  push:
    branches: [main, prod]
    paths-ignore:
      - 'iac/**'
      - '**/*.md'
      - '**/*.txt'
      - 'docs/**'
      - '.github/**'
      - '**/*.yml'

  pull_request:
    branches: [main, prod]
    paths-ignore:
    - 'iac/**'
    - '**/*.md'
    - '**/*.txt'
    - 'docs/**'
    - '.github/**'
    - '**/*.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Compile and Test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java with Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build project
        run: SPRING_PROFILES_ACTIVE=ci ./gradlew build --no-daemon